# Generated by Django 5.1.6 on 2025-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_project_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_table",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="map",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="microplaning",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="report",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
