# Generated by Django 5.1.6 on 2025-02-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_form_created_at_form_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="questions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
