# Generated by Django 5.1.6 on 2025-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_form_questions_alter_form_name_alter_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtag", models.CharField(max_length=10, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("added", models.DateField()),
                ("deprecated", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
