# Generated by Django 5.1.6 on 2025-02-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="default_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_forms",
                to="api.language",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="other_languages",
            field=models.ManyToManyField(
                blank=True, related_name="other_forms", to="api.language"
            ),
        ),
    ]
