# Generated by Django 5.1.6 on 2025-02-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_form_default_language_form_other_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
