# Generated by Django 5.1.6 on 2025-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_form_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="all_questions",
            field=models.JSONField(default=list),
        ),
    ]
