# Generated by Django 5.1.6 on 2025-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_form_all_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="organization_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="organization_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="receive_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
