# Generated by Django 5.1.6 on 2025-05-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_project_active_user_project_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="species",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
