# Generated by Django 5.1.6 on 2025-05-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
