# Generated by Django 5.1.6 on 2025-05-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_organization_project_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="active_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="receive_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
