# Generated by Django 5.1.6 on 2025-05-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_organization_active_user_organization_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forms",
                    models.ManyToManyField(
                        blank=True, related_name="user_profiles", to="api.form"
                    ),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        blank=True, related_name="user_profiles", to="api.organization"
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="user_profiles", to="api.project"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
