# Generated by Django 5.1.6 on 2025-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="data",
        ),
        migrations.AddField(
            model_name="submission",
            name="xml_file",
            field=models.FileField(blank=True, null=True, upload_to="submissions/xml/"),
        ),
    ]
