# Generated by Django 5.1.6 on 2025-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_submission_data_submission_xml_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="form",
        ),
    ]
