# Generated by Django 5.1.6 on 2025-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_submission_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="submission",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
