# Generated by Django 5.1.6 on 2025-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_downloadlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="enketo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
