# Generated by Django 5.1.6 on 2025-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_form_enketo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="allow_anonymous_submissions",
            field=models.BooleanField(default=False),
        ),
    ]
