# Generated by Django 5.1.6 on 2025-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='related_lookup_forms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
