# Generated by Django 5.1.6 on 2025-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_form_related_lookup_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='template_lookup_form_id',
            field=models.IntegerField(blank=True, help_text='ID of the template lookup form this was generated from', null=True),
        ),
    ]
