# Generated by Django 5.1.6 on 2025-07-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_form_template_lookup_form_id_template_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="related_lookup_forms",
        ),
        migrations.AddField(
            model_name="template",
            name="data_collection_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_data_collection",
                to="api.form",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="lookup_forms",
            field=models.ManyToManyField(
                blank=True, related_name="template_lookup_forms", to="api.form"
            ),
        ),
    ]
