# Generated by Django 5.1.6 on 2025-07-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_form_related_lookup_forms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='generated_lookup_forms',
            field=models.ManyToManyField(blank=True, help_text='All lookup forms generated from this template after submission', related_name='template_generated_lookup_forms', to='api.form'),
        ),
    ]
