# Generated by Django 5.1.6 on 2025-08-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_template_generated_lookup_forms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="data",
        ),
        migrations.RemoveField(
            model_name="project",
            name="data_table",
        ),
        migrations.RemoveField(
            model_name="project",
            name="form",
        ),
        migrations.RemoveField(
            model_name="project",
            name="map",
        ),
        migrations.RemoveField(
            model_name="project",
            name="microplaning",
        ),
        migrations.RemoveField(
            model_name="project",
            name="organization_type",
        ),
        migrations.RemoveField(
            model_name="project",
            name="organization_website",
        ),
        migrations.RemoveField(
            model_name="project",
            name="password",
        ),
        migrations.RemoveField(
            model_name="project",
            name="report",
        ),
        migrations.RemoveField(
            model_name="project",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
    ]
