# Generated by Django 5.1.6 on 2025-08-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_remove_form_all_questions_organization_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="criteria",
            field=models.JSONField(
                blank=True,
                help_text="Stores user-selected mandatory question and expected value(s) for lookup forms",
                null=True,
            ),
        ),
    ]
