# Generated by Django 5.1.6 on 2025-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_form_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="form_style",
            field=models.CharField(
                blank=True,
                default="default",
                help_text="Form display style for Enketo (e.g., 'theme-grid', 'pages', etc.)",
                max_length=100,
            ),
        ),
    ]
