# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_form_form_style'),
    ]

    operations = [
        # This migration was auto-generated but had no content
        # Adding empty operations to make it valid
    ]