# Generated by Django 5.1.6 on 2025-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userprofile_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_field',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
