# Generated by Django 5.1.6 on 2025-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userprofile_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='templates',
            field=models.ManyToManyField(blank=True, help_text='Templates assigned to this user through form submissions', related_name='user_profiles', to='api.template'),
        ),
    ]
