# Generated by Django 5.1.6 on 2025-09-03 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0038_create_trashbin_and_patient'),
    ]

    operations = [
        # Create TrashBin model
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', 'Project'), ('form', 'Form'), ('submission', 'Submission'), ('patient', 'Patient'), ('organization', 'Organization'), ('template', 'Template')], help_text='Type of the deleted item', max_length=50)),
                ('item_id', models.PositiveIntegerField(help_text='ID of the deleted item')),
                ('item_name', models.CharField(help_text='Name/title of the deleted item', max_length=255)),
                ('item_data', models.JSONField(help_text='Serialized data of the deleted item')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='When the item was deleted')),
                ('auto_delete_at', models.DateTimeField(help_text='When the item will be automatically deleted')),
                ('deleted_by', models.ForeignKey(help_text='User who deleted the item', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trash Bin Item',
                'verbose_name_plural': 'Trash Bin Items',
                'ordering': ['-deleted_at'],
                'indexes': [
                    models.Index(fields=['item_type', 'item_id'], name='api_trashbi_item_ty_925c5a_idx'),
                    models.Index(fields=['auto_delete_at'], name='api_trashbi_auto_de_f8e3a1_idx'),
                    models.Index(fields=['deleted_by'], name='api_trashbi_deleted_f2b9c8_idx'),
                ],
            },
        ),

        # Add is_deleted field to Patient model if it doesn't exist
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),

        # Add deleted_at field to Patient model if it doesn't exist
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the patient was soft deleted', null=True),
        ),
    ]
