# Generated by Django 5.1.6 on 2025-09-03 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0039_trashbin_patient_is_deleted_patient_deleted_at'),
    ]

    operations = [
        # Add missing fields for restore functionality
        migrations.AddField(
            model_name='trashbin',
            name='restored',
            field=models.BooleanField(default=False, help_text='Whether the item has been restored'),
        ),

        migrations.AddField(
            model_name='trashbin',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='When the item was restored', null=True),
        ),

        migrations.AddField(
            model_name='trashbin',
            name='restored_by',
            field=models.ForeignKey(blank=True, help_text='User who restored the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_trash_items', to=settings.AUTH_USER_MODEL),
        ),

        # Add index for restored field for better performance
        migrations.AddIndex(
            model_name='trashbin',
            index=models.Index(fields=['restored'], name='api_trashbi_restore_a7f2b9_idx'),
        ),
    ]
