# Generated by Django 5.1.6 on 2025-09-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_create_trashbin_and_patient'),
        ('api', '0040_add_restore_fields_to_trashbin'),
    ]

    operations = [
    ]
