# Generated by Django 5.1.6 on 2025-09-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0041_merge_20250908_0125'),
    ]

    operations = [
        # Create Patient model
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient identification from user_identification_11_9943_01976848561', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('submission_data', models.JSONField(blank=True, default=dict, help_text='Latest submission data for this patient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # Create TrashBin model
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('project', 'Project'), ('form', 'Form'), ('submission', 'Submission'), ('patient', 'Patient'), ('organization', 'Organization'), ('template', 'Template')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('item_data', models.JSONField()),
                ('item_name', models.CharField(help_text='Display name for the item', max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('auto_delete_at', models.DateTimeField(help_text='Automatic deletion date (30 days from deletion)')),
                ('restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),

        # Add Patient ManyToMany relationship to Submission
        migrations.AddField(
            model_name='patient',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='patient_records', to='api.submission'),
        ),

        # Add database indexes for TrashBin
        migrations.AddIndex(
            model_name='trashbin',
            index=models.Index(fields=['item_type', 'deleted_at'], name='api_trashbi_item_ty_8e5c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='trashbin',
            index=models.Index(fields=['auto_delete_at'], name='api_trashbi_auto_de_a1f6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='trashbin',
            index=models.Index(fields=['restored'], name='api_trashbi_restore_7e1b85_idx'),
        ),
    ]
