# Generated by Django 5.1.6 on 2025-09-15 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS api_trashbi_item_ty_8e5c6a_idx RENAME TO api_trashbi_item_ty_6474f0_idx;",
            reverse_sql="ALTER INDEX IF EXISTS api_trashbi_item_ty_6474f0_idx RENAME TO api_trashbi_item_ty_8e5c6a_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS api_trashbi_auto_de_a1f6d4_idx RENAME TO api_trashbi_auto_de_6fcceb_idx;",
            reverse_sql="ALTER INDEX IF EXISTS api_trashbi_auto_de_6fcceb_idx RENAME TO api_trashbi_auto_de_a1f6d4_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS api_trashbi_restore_7e1b85_idx RENAME TO api_trashbi_restore_82cc8c_idx;",
            reverse_sql="ALTER INDEX IF EXISTS api_trashbi_restore_82cc8c_idx RENAME TO api_trashbi_restore_7e1b85_idx;",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_form ADD COLUMN IF NOT EXISTS datacollection boolean NOT NULL DEFAULT false;",
                    reverse_sql="ALTER TABLE api_form DROP COLUMN IF EXISTS datacollection;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='form',
                    name='datacollection',
                    field=models.BooleanField(default=False, help_text='True if this is a data collection form'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_form ADD COLUMN IF NOT EXISTS followup boolean NOT NULL DEFAULT false;",
                    reverse_sql="ALTER TABLE api_form DROP COLUMN IF EXISTS followup;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='form',
                    name='followup',
                    field=models.BooleanField(default=False, help_text='True if this is a follow-up form'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_patient ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone;",
                    reverse_sql="ALTER TABLE api_patient DROP COLUMN IF EXISTS deleted_at;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patient',
                    name='deleted_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'api_patient' AND column_name = 'deleted_by_id'
    ) THEN
        ALTER TABLE api_patient ADD COLUMN deleted_by_id integer;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'api_patient_deleted_by_id_fkey'
    ) THEN
        ALTER TABLE api_patient
            ADD CONSTRAINT api_patient_deleted_by_id_fkey
            FOREIGN KEY (deleted_by_id)
            REFERENCES auth_user(id)
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
""",
                    reverse_sql="""
ALTER TABLE api_patient DROP CONSTRAINT IF EXISTS api_patient_deleted_by_id_fkey;
ALTER TABLE api_patient DROP COLUMN IF EXISTS deleted_by_id;
""",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patient',
                    name='deleted_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_items', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_patient ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;",
                    reverse_sql="ALTER TABLE api_patient DROP COLUMN IF EXISTS is_deleted;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patient',
                    name='is_deleted',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
