# Generated by Django 5.1.6 on 2025-12-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_api_trashbi_item_ty_8e5c6a_idx_api_trashbi_item_ty_6474f0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='datacollection',
        ),
        migrations.RemoveField(
            model_name='form',
            name='followup',
        ),
    ]
