# Generated by Django 5.1.6 on 2026-01-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_form_datacollection_remove_form_followup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trashbin',
            new_name='api_trashbi_item_ty_6474f0_idx',
            old_name='api_trashbi_item_ty_8e5c6a_idx',
        ),
        migrations.RenameIndex(
            model_name='trashbin',
            new_name='api_trashbi_auto_de_6fcceb_idx',
            old_name='api_trashbi_auto_de_a1f6d4_idx',
        ),
        migrations.RenameIndex(
            model_name='trashbin',
            new_name='api_trashbi_restore_82cc8c_idx',
            old_name='api_trashbi_restore_7e1b85_idx',
        ),
    ]
