# Generated by Django 5.1.6 on 2026-02-16 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rename_api_trashbi_item_ty_8e5c6a_idx_api_trashbi_item_ty_6474f0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_rows', to='api.form'),
        ),
        migrations.AddField(
            model_name='submission',
            name='instance_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='processing_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='source',
            field=models.CharField(choices=[('openrosa', 'OpenRosa'), ('api', 'API')], default='api', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['form', '-created_at'], name='api_submiss_form_id_1cddd9_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['processing_status', 'created_at'], name='api_submiss_process_37eb31_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['instance_id', 'created_at'], name='api_submiss_instanc_65b0b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('form__isnull', False), ('instance_id__isnull', False), models.Q(('instance_id', ''), _negated=True)), fields=('form', 'instance_id'), name='uniq_submission_form_instance'),
        ),
    ]
