# Generated by Django 5.1.6 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_submission_data_submission_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['form', 'is_deleted', '-created_at'], name='api_submiss_form_id_0356c4_idx'),
        ),
    ]
