# Generated by Django 5.1.6 on 2026-03-31 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auth_user_created_by_column'),
        ('malaria', '0003_village_latitude_village_longitude_village_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_collection_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('microstatification', 'Microstatification')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles_district', to='malaria.district'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_division',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_sk_shw_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_ss_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles_union', to='malaria.union'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles_upazila', to='malaria.upazila'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles_village', to='malaria.village'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='micro_ward_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
