# Generated by Django 5.1.6 on 2026-04-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_userprofile_data_collection_type_and_more'),
        ('malaria', '0005_village_sk_shw_name_village_ss_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='micro_villages',
            field=models.ManyToManyField(blank=True, related_name='user_profiles_villages', to='malaria.village'),
        ),
    ]
