# Generated by Django 5.1.6 on 2026-03-29 09:24

import django.core.validators
import django.db.models.deletion
import malaria.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MalariaUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('sk', 'SK')], max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='malaria_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='NonLocalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jan_cases', models.PositiveIntegerField(default=0)),
                ('feb_cases', models.PositiveIntegerField(default=0)),
                ('mar_cases', models.PositiveIntegerField(default=0)),
                ('apr_cases', models.PositiveIntegerField(default=0)),
                ('may_cases', models.PositiveIntegerField(default=0)),
                ('jun_cases', models.PositiveIntegerField(default=0)),
                ('jul_cases', models.PositiveIntegerField(default=0)),
                ('aug_cases', models.PositiveIntegerField(default=0)),
                ('sep_cases', models.PositiveIntegerField(default=0)),
                ('oct_cases', models.PositiveIntegerField(default=0)),
                ('nov_cases', models.PositiveIntegerField(default=0)),
                ('dec_cases', models.PositiveIntegerField(default=0)),
                ('reporting_year', models.PositiveIntegerField(default=malaria.models.current_year)),
                ('country', models.CharField(default='Bangladesh', max_length=255)),
                ('district_or_state', models.CharField(blank=True, default='', max_length=255)),
                ('upazila_or_township', models.CharField(blank=True, default='', max_length=255)),
                ('union_name', models.CharField(blank=True, default='', max_length=255)),
                ('village_name', models.CharField(blank=True, default='', max_length=255)),
                ('sk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malaria_non_local_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reporting_year', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='malaria.district')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='malaria.upazila')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ward_no', models.CharField(blank=True, max_length=50, null=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='malaria.union')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jan_cases', models.PositiveIntegerField(default=0)),
                ('feb_cases', models.PositiveIntegerField(default=0)),
                ('mar_cases', models.PositiveIntegerField(default=0)),
                ('apr_cases', models.PositiveIntegerField(default=0)),
                ('may_cases', models.PositiveIntegerField(default=0)),
                ('jun_cases', models.PositiveIntegerField(default=0)),
                ('jul_cases', models.PositiveIntegerField(default=0)),
                ('aug_cases', models.PositiveIntegerField(default=0)),
                ('sep_cases', models.PositiveIntegerField(default=0)),
                ('oct_cases', models.PositiveIntegerField(default=0)),
                ('nov_cases', models.PositiveIntegerField(default=0)),
                ('dec_cases', models.PositiveIntegerField(default=0)),
                ('reporting_year', models.PositiveIntegerField(default=malaria.models.current_year)),
                ('hh', models.PositiveIntegerField(default=0)),
                ('population', models.PositiveIntegerField(default=0)),
                ('itn_2023', models.PositiveIntegerField(default=0)),
                ('itn_2024', models.PositiveIntegerField(default=0)),
                ('itn_2025', models.PositiveIntegerField(default=0)),
                ('sk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malaria_local_records', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_records', to='malaria.village')),
            ],
            options={
                'ordering': ('-reporting_year', 'village__name'),
            },
        ),
        migrations.CreateModel(
            name='MonthlyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_year', models.PositiveIntegerField(default=malaria.models.current_year)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='APPROVED', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malaria_monthly_approvals', to=settings.AUTH_USER_MODEL)),
                ('local_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_approvals', to='malaria.localrecord')),
                ('non_local_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_approvals', to='malaria.nonlocalrecord')),
            ],
            options={
                'ordering': ('reporting_year', 'month'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('local_record__isnull', False), ('non_local_record__isnull', True)), models.Q(('local_record__isnull', True), ('non_local_record__isnull', False)), _connector='OR'), name='malaria_monthly_approval_exactly_one_record'), models.UniqueConstraint(condition=models.Q(('local_record__isnull', False)), fields=('local_record', 'reporting_year', 'month'), name='malaria_unique_local_monthly_approval'), models.UniqueConstraint(condition=models.Q(('non_local_record__isnull', False)), fields=('non_local_record', 'reporting_year', 'month'), name='malaria_unique_non_local_monthly_approval')],
            },
        ),
        migrations.AddConstraint(
            model_name='upazila',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='malaria_unique_upazila_per_district'),
        ),
        migrations.AddConstraint(
            model_name='union',
            constraint=models.UniqueConstraint(fields=('upazila', 'name'), name='malaria_unique_union_per_upazila'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('union', 'name', 'ward_no'), name='malaria_unique_village_per_union_and_ward'),
        ),
        migrations.AddConstraint(
            model_name='localrecord',
            constraint=models.UniqueConstraint(fields=('village', 'reporting_year'), name='malaria_unique_local_record_per_village_year'),
        ),
    ]
