# Generated by Django 5.1.6 on 2026-03-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0002_backfill_malaria_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='name_bn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='village_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
