# Generated by Django 5.1.6 on 2026-04-01 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0003_village_latitude_village_longitude_village_name_bn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrostatificationDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.CharField(choices=[('Bandarban', 'Bandarban'), ('Khagrachhari', 'Khagrachhari'), ("Cox's Bazar", "Cox's Bazar"), ('Rangamati', 'Rangamati'), ('Chattogram', 'Chattogram')], max_length=255)),
                ('excel_file', models.FileField(upload_to='microstatification_uploads/%Y/%m/%d/')),
                ('parsed_data', models.JSONField(default=dict, help_text='Parsed Excel data structure with villages/unions/upazilas')),
                ('districts_created', models.IntegerField(default=0)),
                ('upazilas_created', models.IntegerField(default=0)),
                ('unions_created', models.IntegerField(default=0)),
                ('villages_created', models.IntegerField(default=0)),
                ('villages_updated', models.IntegerField(default=0)),
                ('upload_note', models.TextField(blank=True, default='', help_text='Any notes or errors during upload')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microstatification_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
