# Generated by Django 5.1.6 on 2026-04-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0004_microstatificationdataupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='sk_shw_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='ss_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
