# Generated by Django 5.1.6 on 2026-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0005_village_sk_shw_name_village_ss_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='bordering_country_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='distance_from_upazila_office_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='mmw_hp_chwc_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='other_activities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
