# Generated by Django 5.1.6 on 2026-04-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0007_localrecord_itn_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyapproval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
    ]
