# Generated by Django 5.1.6 on 2026-04-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0009_monthaccesssetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthaccesssetting',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
