# Generated by Django 5.1.6 on 2026-04-28 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0011_village_unique_with_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='localrecord',
            index=models.Index(fields=['reporting_year'], name='malaria_local_year_idx'),
        ),
        migrations.AddIndex(
            model_name='localrecord',
            index=models.Index(fields=['sk_user', 'reporting_year'], name='malaria_local_user_year_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyapproval',
            index=models.Index(fields=['reporting_year'], name='malaria_approval_year_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyapproval',
            index=models.Index(fields=['reporting_year', 'status', 'month'], name='mal_appr_year_stat_mon_idx'),
        ),
        migrations.AddIndex(
            model_name='nonlocalrecord',
            index=models.Index(fields=['reporting_year'], name='malaria_nonlocal_year_idx'),
        ),
        migrations.AddIndex(
            model_name='nonlocalrecord',
            index=models.Index(fields=['sk_user', 'reporting_year'], name='malaria_nonlocal_user_year_idx'),
        ),
    ]
